include intellij

diff --git a/build/Dockerfile b/build/Dockerfile
--- a/build/Dockerfile
+++ b/build/Dockerfile
@@ -1,21 +1,44 @@
-#-----------------------------------------------------------------------------------------
-# Copyright (c) Microsoft Corporation. All rights reserved.
-# Licensed under the MIT License. See LICENSE in the project root for license information.
-#-----------------------------------------------------------------------------------------
+FROM ubuntu:20.04
 
-FROM codercom/enterprise-intellij:ubuntu
+SHELL ["/bin/bash", "-c"]
 
 USER root
 
-# Verify git, process tools installed
-RUN apt-get update
+# Install baseline packages
+RUN apt-get update && \
+    DEBIAN_FRONTEND="noninteractive" apt-get install --yes \
+      bash \
+      build-essential \
+      ca-certificates \
+      curl \
+      docker.io \
+      htop \
+      locales \
+      man \
+      python3 \
+      python3-pip \
+      software-properties-common \
+      sudo \
+      systemd \
+      systemd-sysv \
+      unzip \
+      jq \
+      git jq procps ftp sqlite3 netcat \
+      tzdata openssh-server \
+      libxtst6 libxrender1 libxi6 libgtk-3-0 libfontconfig1 \
+      vim \
+      wget && \
+    # Install latest Git using their official PPA
+    add-apt-repository ppa:git-core/ppa && \
+    DEBIAN_FRONTEND="noninteractive" apt-get install --yes git
 
-# Install: git, jq, sqlite, python
-RUN apt-get -yq install sudo git jq procps ftp sqlite3 netcat
-RUN apt-get -yq install build-essential tzdata python3-pip ffmpeg openssh-server
+# Enables Docker starting with systemd
+RUN systemctl enable docker
 
-## Add other prereqs here
-# RUN apt-get -yq install some-package
+# Add docker-compose
+RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+RUN chmod +x /usr/local/bin/docker-compose
+
 
 
 ## Setup Node
@@ -26,18 +49,73 @@ RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg |  apt-key add - && \
 
 RUN npm install -g browserify watchify yarn
 
-# Clean up
-RUN apt-get autoremove -y \
-    && apt-get clean -y \
+# setup Go
+
+RUN curl -OL https://golang.org/dl/go1.16.7.linux-amd64.tar.gz
+RUN tar -C /usr/local -xvf go1.16.7.linux-amd64.tar.gz
+RUN ln -s /usr/local/go/bin/go /usr/local/bin/go
+
+# setup Java
+
+
+ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
+
+RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata curl ca-certificates fontconfig locales \
+    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
+    && locale-gen en_US.UTF-8 \
     && rm -rf /var/lib/apt/lists/*
+
+ENV JAVA_VERSION jdk-11.0.11+9
+
+RUN set -eux; \
+    ARCH="$(dpkg --print-architecture)"; \
+    case "${ARCH}" in \
+       aarch64|arm64) \
+         ESUM='4966b0df9406b7041e14316e04c9579806832fafa02c5d3bd1842163b7f2353a'; \
+         BINARY_URL='https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_aarch64_linux_hotspot_11.0.11_9.tar.gz'; \
+         ;; \
+       armhf|armv7l) \
+         ESUM='2d7aba0b9ea287145ad437d4b3035fc84f7508e78c6fec99be4ff59fe1b6fc0d'; \
+         BINARY_URL='https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_arm_linux_hotspot_11.0.11_9.tar.gz'; \
+         ;; \
+       ppc64el|ppc64le) \
+         ESUM='945b114bd0a617d742653ac1ae89d35384bf89389046a44681109cf8e4f4af91'; \
+         BINARY_URL='https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_ppc64le_linux_hotspot_11.0.11_9.tar.gz'; \
+         ;; \
+       s390x) \
+         ESUM='5d81979d27d9d8b3ed5bca1a91fc899cbbfb3d907f445ee7329628105e92f52c'; \
+         BINARY_URL='https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_s390x_linux_hotspot_11.0.11_9.tar.gz'; \
+         ;; \
+       amd64|x86_64) \
+         ESUM='e99b98f851541202ab64401594901e583b764e368814320eba442095251e78cb'; \
+         BINARY_URL='https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.11_9.tar.gz'; \
+         ;; \
+       *) \
+         echo "Unsupported arch: ${ARCH}"; \
+         exit 1; \
+         ;; \
+    esac; \
+    curl -LfsSo /tmp/openjdk.tar.gz ${BINARY_URL}; \
+    echo "${ESUM} */tmp/openjdk.tar.gz" | sha256sum -c -; \
+    mkdir -p /opt/java/openjdk; \
+    cd /opt/java/openjdk; \
+    tar -xf /tmp/openjdk.tar.gz --strip-components=1; \
+    rm -rf /tmp/openjdk.tar.gz;
+
+ENV JAVA_HOME=/opt/java/openjdk \
+    PATH="/opt/java/openjdk/bin:$PATH"
+
+RUN echo "JAVA_HOME=/opt/java/openjdk" >> /etc/environment
+RUN echo "PATH=/opt/java/openjdk/bin:$PATH" >> /etc/environment
+
 
 
 # # Install IntelliJ stuff
 
 # # Run everything as root
-# # USER root
+USER root
 
-# # Packages required for multi-editor support
+# Packages required for multi-editor support
 # RUN apt-get install -yq \
 #     libxtst6 \
 #     libxrender1 \
@@ -45,14 +123,21 @@ RUN apt-get autoremove -y \
 #     libxi6 \
 #     libgtk-3-0
 
-# # Install intellij
-# RUN mkdir -p /opt/idea
-# RUN curl -L "https://download.jetbrains.com/product?code=IIC&latest&distribution=linux" | tar -C /opt/idea --strip-components 1 -xzvf -
+# Install intellij
+RUN mkdir -p /opt/idea
+RUN curl -L "https://download.jetbrains.com/product?code=IIC&latest&distribution=linux" | tar -C /opt/idea --strip-components 1 -xzvf -
 
 # # Add a binary to the PATH that points to the intellij startup script.
-# RUN ln -s /opt/idea/bin/idea.sh /usr/bin/intellij-idea-community
+RUN ln -s /opt/idea/bin/idea.sh /usr/bin/intellij-idea-community
 
 
+# Add VSCode-server
+RUN curl -fsSL https://code-server.dev/install.sh | sh
+
+# Clean up
+RUN apt-get autoremove -y \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/*
 
 ##
 ## WARNING! Docker-Env needs all of the settings
